language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: Y+4DKtM/e3BvsqQvm52CB/gZxNTG52J7Hx3686gEwhuv84cktwPe8znO3G9HNSB8WhfO1ON1NUAwBY+fKEg7UDlbj4keL25z0wzNeZoon8ImoK2D7RCoM0EGN7uOQrR0IbXQAEV+SqjBOH0FVq/1jA9Y5V+E3e+FkCZWfssIvsfzN3aHtJZQ/xvWwvjJ85UquARPgDSd5PL4AIlAytkUuChakMRWFfnEKpO/IUTW4Oae9xW63c1DPedmPFGUNA9C48h4FpnpaahG4wPfr749B1K8e2k4C5yBVIKgVyZNNDTPyurIK2IWPqeNFzrtVHxaq8YBdwOt5ptP6Z2o9wPN05VrEXxgpfkS6znDRZm1p7ME8H6OzznExyi8d1OHN4Vwiea2DvGQGiCTpA2YdQd2qBrZWtQO2Mfr2Pfj/xMhdkzLNTOlLCbNtFiBsyOTaIJ+nlVkOZLnpb3xJ9AETyyUBpf5bXcRdSR7Z1BT5HjYsRNX4MRVuieZJZhdPAlGL1eJBER9nFyQxWGQiffif+i0keKitUjj6v4LQKNOmtypjLoDg/NRVFfJjSWwfYdQmCvy//Na/4ar0GjCRCWN2slk1fCNhmGanb+uLMpQSK1CPFwUCELVTDzKbaEYzWvK77JrOSEUgLOkuRfwDYgcEdP0DoYJS2ZsszFiwzEMf94ndJo=
  app: imp-sei-cw-1
