language: java
jdk:
- openjdk8
script: mvn clean verify
deploy:
  provider: heroku
  api_key:
    secure: dcf3mpzRigc8S7DPbfHFLCFBk4ziI23GhbCpJuOr3zOOr1JKYvISbObVh5NWnyNRm9TGpwY95k+Pxh3VeIHvEztzjeI29S8OXdyZTHGsxFnBQ9CKgROVDzRmzQuxPfCs9ksEVowiAp2rd4tMpHa3IcENN7Ls/aY+Oy5VMosmkU52XAqZu4n1/Q99cg8v8v+BOXRXgNhVCH8xVObEHKryBSjhbQVSTuaiDdokID+MlmW1VXWZokjx5Wzxlaa2ngwLsMq+resBDspxoSrnWQbO2hhxRVJVYnPlveEmEppS5O9aqRzq3tZ64Fxcc9u3Nz/2kc9PGIVdR6Zq7uNamiSpVKNBnUtCykbyHScPPYyT651xKcFdXoJahDLXMfYCV9saKvEQE1c/BeOPrQ/wvj/HsyuYz+Gpf1bRpWCbsgIpwi8v5CtHY74F2a8MADjlzKtI5XY93NBCJU9nEEybaQQuN2c+mh2s9NbxEbOrvNhxROqizSJRXByJpI+7pQYQD5REBAKqsn5o1E9uFHyXklV8ksKsKQnQCFSUiUtgiGhRFdO5iEZ178rxKImNF+N+dGuFUa1cTnOS/rFOTOt1QHkgtugeYClVAcBMKIr4wtR7jUkwx2WVpe8xrOOOlMZx3o+IgHdipCwRYmx07ebUBThVwf9nBqPZg0eYb6kCZltjT4A=
  app: imp-sei-cw-1
